"""Domain-layer models and pure transformations."""

from .config import (
    AngleConstraint,
    BiHandRetargetingConfig,
    BiHandViewerConfig,
    ControllerConfig,
    HandConfig,
    PinchConfig,
    PositionConfig,
    PositionConstraint,
    PreprocessConfig,
    RetargetingConfig,
    SolverConfig,
    VectorLossConfig,
)
from .control import ControllerBackend, HandCommand, HandState
from .hand_side import HAND_SIDES, HandSide, display_hand_side, normalize_hand_side
from .models import (
    BiHandFrame,
    BiHandFrameSink,
    BiHandOutputSink,
    BiHandRetargetingResult,
    BiHandSessionSummary,
    BiHandSourceFrame,
    BiHandTrackingSource,
    HandFrame,
    HandFrameSink,
    HandTrackingSource,
    OutputSink,
    PreviewWindow,
    RetargetingStepResult,
    SessionSummary,
    SourceFrame,
)
from .preprocessing import compute_target_directions, preprocess_landmarks

__all__ = [
    "AngleConstraint",
    "BiHandFrame",
    "BiHandFrameSink",
    "BiHandOutputSink",
    "BiHandRetargetingConfig",
    "BiHandRetargetingResult",
    "BiHandSessionSummary",
    "BiHandSourceFrame",
    "BiHandTrackingSource",
    "BiHandViewerConfig",
    "ControllerBackend",
    "ControllerConfig",
    "display_hand_side",
    "HandConfig",
    "HandCommand",
    "HandFrame",
    "HandFrameSink",
    "HAND_SIDES",
    "HandSide",
    "HandState",
    "HandTrackingSource",
    "normalize_hand_side",
    "OutputSink",
    "PinchConfig",
    "PositionConfig",
    "PositionConstraint",
    "PreviewWindow",
    "PreprocessConfig",
    "RetargetingConfig",
    "RetargetingStepResult",
    "SessionSummary",
    "SolverConfig",
    "SourceFrame",
    "compute_target_directions",
    "preprocess_landmarks",
    "VectorLossConfig",
]
