hand:
  name: dexhand021_right
  side: right
  mjcf_path: ../../../assets/mjcf/dexhand021_right/model.xml
retargeting:
  type: vector
  vector_loss:
    type: residual
    huber_delta: 0.02
    scaling: 1.0
    scale_landmarks:
    - 0
    - 9
    scale_bodies:
    - world
    - f_link3_2
    scale_body_types:
    - body
    - body
  preprocess:
    temporal_filter_alpha: 0.65
  solver:
    max_iterations: 60
    norm_delta: 0.001
    output_alpha: 0.92
  vector_constraints:
  - human:
    - 0
    - 4
    robot:
    - world
    - f_link1_4_tip
    weight: 2.2
    robot_types:
    - body
    - site
  - human:
    - 5
    - 6
    robot:
    - f_link2_1
    - f_link2_2
    weight: 1.0
  - human:
    - 6
    - 8
    robot:
    - f_link2_2
    - f_link2_4_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 7
    - 8
    robot:
    - f_link2_3
    - f_link2_4_tip
    weight: 0.8
    robot_types:
    - body
    - site
  - human:
    - 9
    - 10
    robot:
    - f_link3_1
    - f_link3_2
    weight: 1.0
  - human:
    - 10
    - 12
    robot:
    - f_link3_2
    - f_link3_4_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 11
    - 12
    robot:
    - f_link3_3
    - f_link3_4_tip
    weight: 0.8
    robot_types:
    - body
    - site
  - human:
    - 13
    - 14
    robot:
    - f_link4_1
    - f_link4_2
    weight: 1.0
  - human:
    - 14
    - 16
    robot:
    - f_link4_2
    - f_link4_4_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 15
    - 16
    robot:
    - f_link4_3
    - f_link4_4_tip
    weight: 0.8
    robot_types:
    - body
    - site
  - human:
    - 17
    - 18
    robot:
    - f_link5_1
    - f_link5_2
    weight: 1.0
  - human:
    - 18
    - 20
    robot:
    - f_link5_2
    - f_link5_4_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 19
    - 20
    robot:
    - f_link5_3
    - f_link5_4_tip
    weight: 0.8
    robot_types:
    - body
    - site
  frame_constraints:
  - name: thumb_cmc_frame
    human_origin: 1
    human_primary: 2
    human_secondary: 5
    robot_origin: f_link1_2
    robot_primary: f_link1_3
    robot_secondary: f_link2_1
    primary_weight: 2.0
    secondary_weight: 1.8
  distance_constraints:
  - human: [4, 8]
    robot: [f_link1_4_tip, f_link2_4_tip]
    robot_types: [site, site]
    weight: 2000.0
    scale: 1.0
    threshold: 0.04
  - human: [4, 12]
    robot: [f_link1_4_tip, f_link3_4_tip]
    robot_types: [site, site]
    weight: 1500.0
    scale: 1.0
    threshold: 0.04
  - human: [4, 16]
    robot: [f_link1_4_tip, f_link4_4_tip]
    robot_types: [site, site]
    weight: 1000.0
    scale: 1.0
    threshold: 0.04
  - human: [4, 20]
    robot: [f_link1_4_tip, f_link5_4_tip]
    robot_types: [site, site]
    weight: 800.0
    scale: 1.0
    threshold: 0.04
