hand:
  name: linkerhand_lhg20_left
  side: left
  mjcf_path: ../../../assets/mjcf/linkerhand_lhg20_left/model.xml
retargeting:
  type: vector
  angle_constraints:
  - landmarks:
    - 1
    - 2
    - 3
    joint: thumb_mcp
    weight: 0.5
  - landmarks:
    - 2
    - 3
    - 4
    joint: thumb_dip
    weight: 0.5
  - landmarks:
    - 5
    - 6
    - 7
    joint: index_pip
    weight: 2.0
  - landmarks:
    - 6
    - 7
    - 8
    joint: index_dip
    weight: 2.0
  - landmarks:
    - 9
    - 10
    - 11
    joint: middle_pip
    weight: 2.0
  - landmarks:
    - 10
    - 11
    - 12
    joint: middle_dip
    weight: 2.0
  - landmarks:
    - 13
    - 14
    - 15
    joint: ring_pip
    weight: 2.0
  - landmarks:
    - 14
    - 15
    - 16
    joint: ring_dip
    weight: 2.0
  - landmarks:
    - 17
    - 18
    - 19
    joint: pinky_pip
    weight: 2.0
  - landmarks:
    - 18
    - 19
    - 20
    joint: pinky_dip
    weight: 2.0
  preprocess:
    temporal_filter_alpha: 0.65
  solver:
    max_iterations: 60
    norm_delta: 0.001
    output_alpha: 0.92
  vector_constraints:
  - human:
    - 0
    - 5
    robot:
    - world
    - index_proximal
    weight: 1.0
  - human:
    - 0
    - 9
    robot:
    - world
    - middle_proximal
    weight: 1.0
  - human:
    - 0
    - 13
    robot:
    - world
    - ring_proximal
    weight: 1.0
  - human:
    - 0
    - 17
    robot:
    - world
    - pinky_proximal
    weight: 1.0
  - human:
    - 0
    - 4
    robot:
    - world
    - thumb_distal_tip
    weight: 2.5
    robot_types:
    - body
    - site
  - human:
    - 5
    - 6
    robot:
    - index_metacarpals
    - index_middle
    weight: 1.0
  - human:
    - 6
    - 8
    robot:
    - index_proximal
    - index_distal_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 7
    - 8
    robot:
    - index_distal
    - index_distal_tip
    weight: 0.8
    robot_types:
    - body
    - site
  - human:
    - 9
    - 10
    robot:
    - middle_metacarpals
    - middle_middle
    weight: 1.0
  - human:
    - 10
    - 12
    robot:
    - middle_proximal
    - middle_distal_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 11
    - 12
    robot:
    - middle_distal
    - middle_distal_tip
    weight: 0.8
    robot_types:
    - body
    - site
  - human:
    - 13
    - 14
    robot:
    - ring_metacarpals
    - ring_middle
    weight: 1.0
  - human:
    - 14
    - 16
    robot:
    - ring_proximal
    - ring_distal_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 15
    - 16
    robot:
    - ring_distal
    - ring_distal_tip
    weight: 0.8
    robot_types:
    - body
    - site
  - human:
    - 17
    - 18
    robot:
    - pinky_metacarpals
    - pinky_middle
    weight: 1.0
  - human:
    - 18
    - 20
    robot:
    - pinky_proximal
    - pinky_distal_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 19
    - 20
    robot:
    - pinky_distal
    - pinky_distal_tip
    weight: 0.8
    robot_types:
    - body
    - site
  frame_constraints:
  - name: thumb_cmc_frame
    human_origin: 1
    human_primary: 2
    human_secondary: 5
    robot_origin: thumb_metacarpals
    robot_primary: thumb_proximal
    robot_secondary: index_proximal
    primary_weight: 2.0
    secondary_weight: 1.8
  distance_constraints:
  - human:
    - 4
    - 8
    robot:
    - thumb_distal_tip
    - index_distal_tip
    robot_types:
    - site
    - site
    weight: 2000.0
    scale: 1.0
    threshold: 0.04
  - human:
    - 4
    - 12
    robot:
    - thumb_distal_tip
    - middle_distal_tip
    robot_types:
    - site
    - site
    weight: 1500.0
    scale: 1.0
    threshold: 0.04
  - human:
    - 4
    - 16
    robot:
    - thumb_distal_tip
    - ring_distal_tip
    robot_types:
    - site
    - site
    weight: 1000.0
    scale: 1.0
    threshold: 0.04
  - human:
    - 4
    - 20
    robot:
    - thumb_distal_tip
    - pinky_distal_tip
    robot_types:
    - site
    - site
    weight: 800.0
    scale: 1.0
    threshold: 0.04
