hand:
  name: revo2_right
  side: right
  mjcf_path: ../../../assets/mjcf/revo2_right/model.xml
retargeting:
  type: vector
  vector_loss:
    type: residual
    huber_delta: 0.02
    scaling: 1.0
    scale_landmarks:
    - 0
    - 9
    scale_bodies:
    - world
    - middle_proximal_link
    scale_body_types:
    - body
    - body
  preprocess:
    temporal_filter_alpha: 0.45
  solver:
    max_iterations: 50
    norm_delta: 0.004
    output_alpha: 0.8
  vector_constraints:
  - human:
    - 0
    - 5
    robot:
    - world
    - index_proximal_link
    weight: 1.0
  - human:
    - 0
    - 9
    robot:
    - world
    - middle_proximal_link
    weight: 1.0
  - human:
    - 0
    - 13
    robot:
    - world
    - ring_proximal_link
    weight: 1.0
  - human:
    - 0
    - 17
    robot:
    - world
    - pinky_proximal_link
    weight: 1.0
  - human:
    - 0
    - 4
    robot:
    - world
    - thumb_distal_link_tip
    weight: 2.0
    robot_types:
    - body
    - site
  - human:
    - 1
    - 4
    robot:
    - thumb_metacarpal_link
    - thumb_distal_link_tip
    weight: 1.6
    robot_types:
    - body
    - site
  - human:
    - 2
    - 4
    robot:
    - thumb_proximal_link
    - thumb_distal_link_tip
    weight: 1.4
    robot_types:
    - body
    - site
  - human:
    - 3
    - 4
    robot:
    - thumb_distal_link
    - thumb_distal_link_tip
    weight: 1.2
    robot_types:
    - body
    - site
  - human:
    - 5
    - 6
    robot:
    - index_proximal_link
    - index_distal_link
    weight: 1.0
  - human:
    - 6
    - 8
    robot:
    - index_distal_link
    - index_distal_link_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 9
    - 10
    robot:
    - middle_proximal_link
    - middle_distal_link
    weight: 1.0
  - human:
    - 10
    - 12
    robot:
    - middle_distal_link
    - middle_distal_link_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 13
    - 14
    robot:
    - ring_proximal_link
    - ring_distal_link
    weight: 1.0
  - human:
    - 14
    - 16
    robot:
    - ring_distal_link
    - ring_distal_link_tip
    weight: 1.0
    robot_types:
    - body
    - site
  - human:
    - 17
    - 18
    robot:
    - pinky_proximal_link
    - pinky_distal_link
    weight: 1.0
  - human:
    - 18
    - 20
    robot:
    - pinky_distal_link
    - pinky_distal_link_tip
    weight: 1.0
    robot_types:
    - body
    - site
  frame_constraints:
  - name: thumb_cmc_frame
    human_origin: 1
    human_primary: 2
    human_secondary: 5
    robot_origin: thumb_metacarpal_link
    robot_primary: thumb_proximal_link
    robot_secondary: index_proximal_link
    primary_weight: 1.2
    secondary_weight: 1.0
